services:
  backend:
    build:
      context: .
      dockerfile: ./million_backend/Dockerfile
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: rebuild
          path: ./million_backend
  frontend:
    build:
      context: .
      dockerfile: ./million_client/Dockerfile
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: rebuild
          path: ./million_client
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USER=million_search
      - POSTGRES_PASSWORD=password1234
    ports:
      - '5432:5432'
    volumes:
      - 'database_data:/var/lib/pgsql/data'
  search:
    image: 'getmeili/meilisearch:latest'
    environment:
      - MEILI_ENV=development
    volumes:
      - 'search_data:/meili_data'
    ports:
      - '7700:7700'

volumes:
  database_data:
    driver: local
  search_data:
    driver: local
