services:
    backend:
        build: 
            context: .
            dockerfile: ./million_backend/Dockerfile
        ports:
            - "8080:8080"
        links:
          - "database:database"
        develop:
          watch:
            - action: rebuild
              path: ./million_backend

    database:
        image: "postgres:16.2"
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_USER=million_search
            - POSTGRES_PASSWORD=password1234
        ports:
            - "5432:5432"
