services:
    backend:
        build: 
            context: .
            dockerfile: ./million_backend
        ports:
            - "8080:8080"
        networks:
            - internal
        develop:
          watch:
            - action: rebuild
              path: ./million_backend              
    database:
        image: "postgres:16.2"
        networks:
            - internal
        restart: always
        shm_size: 128mb
        environment:
            - POSTGRES_PASSWORD=password1234
    work_queue:
        image: "rabbitmq:3.13.1"
        networks:
            - internal
        
networks:
    internal:
  