services:
  backend:
    build:
      context: .
      dockerfile: ./million_backend/Dockerfile
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: rebuild
          path: ./million_backend
    depends_on:
      - database
      - meilisearch
      - meilisync
  frontend:
    build:
      context: .
      dockerfile: ./million_client/Dockerfile
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: rebuild
          path: ./million_client
    depends_on:
      - backend
          
  database:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    environment:
      - POSTGRES_USER=million_search
      - POSTGRES_PASSWORD=password1234
    ports:
      - '5432:5432'
    volumes:
      - 'database_data:/var/lib/postgresql/data'
  meilisearch:
    image: 'getmeili/meilisearch:latest'
    environment:
      - MEILI_ENV=development
    volumes:
      - 'search_data:/meili_data'
    ports:
      - '7700:7700'
    # depends_on:
    #   - meilisync

  meilisync:
    image: long2ice/meilisync:sha-052c4de
    volumes:
      - ./meilisync_config.yml:/meilisync/config.yml
    depends_on:
      - database
      - meilisearch

volumes:
  database_data:
    driver: local
  search_data:
    driver: local
