debug: true

source:
  type: postgres
  host: database
  port: 5432
  user: million_search
  password: "password1234"
  database: million_search
meilisearch:
  api_url: http://meilisearch:7700/
  api_key: '8BG2dieXqsN4e8CXFUnab89M8u-T0_BREDE8tY3AeDQ'
  insert_size: 1000
  insert_interval: 10
sync:
- table: websites
  index: websites
  pk: id
  full: true
- table: image
  index: image
  pk: id
  full: true
- table: video
  index: video
  pk: id
  full: true
- table: audio
  index: audio
  pk: id
  full: true

progress:
  type: file
