debug: true

source:
  type: postgres
  host: database
  port: 5432
  user: million_search
  password: "password1234"
  database: million_search
meilisearch:
  api_url: http://meilisearch:7700/
  api_key: '-r_i6i4t88jTzlWtNIyVr0VybDBdn2it428fxr2Blcg'
  insert_size: 1000
  insert_interval: 10
sync:
- table: websites
  index: websites
  pk: id
  full: true
  fields:
    id:
    url:
    title:
    description:
    text_fields:
    sections:

- table: image
  index: image
  pk: id
  full: true
  fields:
    id:
    url:
    alt_text:


- table: search_history
  index: search_history
  pk: id
  full: true
  fields:
    id:
    text:
    count:


progress:
  type: file
