debug: true

source:
  type: postgres
  host: database
  port: 5432
  user: million_search
  password: "password1234"
  database: million_search
meilisearch:
  api_url: http://meilisearch:7700/
  api_key: '4m-VT7nEPBGNEbM9nJWKRaeqB6o2tgmUwlbJjqPNx2E'
  insert_size: 1000
  insert_interval: 10
sync:
- table: websites
  index: websites
  pk: id
  full: true
  fields:
    id:
    url:
    title:
    description:
    sections:

- table: image
  index: image
  pk: id
  full: true
  fields:
    id:
    url:

- table: video
  index: video
  pk: id
  full: true
  fields:
    id:
    url:

- table: audio
  index: audio
  pk: id
  full: true
  fields:
    id:
    url:

- table: search_history
  index: audio
  pk: id
  full: true
  fields:
    id:
    text:

progress:
  type: file
