//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "image")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub url: String,
    pub source: i32,
    pub width: Option<i32>,
    pub height: Option<i32>,
    pub alt_text: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::websites::Entity",
        from = "Column::Source",
        to = "super::websites::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Websites,
}

impl Related<super::websites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Websites.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
