//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod audio;
pub mod crawler_queue;
pub mod image;
pub mod manifest;
pub mod search_history;
pub mod video;
pub mod websites;
