//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::audio::Entity as Audio;
pub use super::crawler_queue::Entity as CrawlerQueue;
pub use super::image::Entity as Image;
pub use super::post::Entity as Post;
pub use super::search_history::Entity as SearchHistory;
pub use super::video::Entity as Video;
pub use super::websites::Entity as Websites;
